name: PR checks
on: pull_request

jobs:
  run-image:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: DOCKER_BUILDKIT=1 docker build --tag cloud-init .

    - name: Run image
      run: |
        docker run -d -p 80:80 cloud-init
        sleep 1
        curl --head --fail --retry-delay 5 --retry 10 --retry-connrefused http://localhost

  lint-nginx:
=======

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build --tag cloud-init-io .

      - name: Run image
        run: |
          docker run --detach --publish 80:80 cloud-init-io
          sleep 1
          curl --head --fail --retry-delay 1 --retry 30 --retry-connrefused http://localhost

  run-dotrun:
>>>>>>> Switch Jekyll to eleventy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

<<<<<<< HEAD
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install gixy
        run: pip3 install gixy

      - name: Lint nginx configuration files
        run: yarn lint-nginx
=======
      - name: Install dotrun
        run: |
          sudo snap install dotrun
          sudo chown root:root /

      - name: Install dependencies
        run: /snap/bin/dotrun install

      - name: Build assets
        run: /snap/bin/dotrun build

      - name: Run dotrun
        run: |
          /snap/bin/dotrun &
          curl --head --fail --retry-delay 1 --retry 30 --retry-connrefused http://localhost:8009
>>>>>>> Switch Jekyll to eleventy

  lint-scss:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint scss
        run: yarn lint-scss
<<<<<<< HEAD
=======

  lint-nginx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn install --immutable
          sudo apt-get install python3-setuptools
          pip3 install gixy

      - name: Test nginx
        run: yarn lint-nginx
>>>>>>> Switch Jekyll to eleventy
